name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Environment variables available to all jobs and steps
env:
  VITE_LEMON_SQUEEZY_API_KEY: ${{ secrets.VITE_LEMON_SQUEEZY_API_KEY }}
  VITE_LEMON_SQUEEZY_STORE_ID: ${{ secrets.VITE_LEMON_SQUEEZY_STORE_ID }}
  VITE_LEMON_SQUEEZY_VARIANT_ID: ${{ secrets.VITE_LEMON_SQUEEZY_VARIANT_ID }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm list typescript
          npm list vite
          
      - name: Debug Environment
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "TypeScript version: $(npx tsc --version)"
          echo "Working directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          
      - name: TypeScript Check
        run: |
          echo "Running TypeScript compilation check..."
          npx tsc --noEmit
          
      - name: Build
        run: |
          echo "Checking environment variables:"
          echo "API key length: ${#VITE_LEMON_SQUEEZY_API_KEY}"
          echo "Store ID is set: ${VITE_LEMON_SQUEEZY_STORE_ID:+yes}"
          echo "Variant ID is set: ${VITE_LEMON_SQUEEZY_VARIANT_ID:+yes}"
          echo "Environment variables:"
          env | grep VITE_ || true
          
          # Create .env file for Vite
          echo "VITE_LEMON_SQUEEZY_API_KEY=$VITE_LEMON_SQUEEZY_API_KEY" > .env
          echo "VITE_LEMON_SQUEEZY_STORE_ID=$VITE_LEMON_SQUEEZY_STORE_ID" >> .env
          echo "VITE_LEMON_SQUEEZY_VARIANT_ID=$VITE_LEMON_SQUEEZY_VARIANT_ID" >> .env
          
          # Run build with debug output
          npm run build --debug
          
          echo "Build completed. Checking dist directory:"
          ls -la dist/
          
          if [ ! -f dist/index.html ]; then
            echo "Error: dist/index.html not found!"
            exit 1
          fi
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 